main: hello1.asm
	\masm32\bin\ml /c /coff /Cp hello1.asm
	\masm32\bin\link -entry:main /subsystem:console hello1.obj
	hello1

main2: hello3.asm
	\masm32\bin\ml /c /coff /Cp hello3.asm
	\masm32\bin\link -entry:main /subsystem:console hello3.obj
	hello3

main3: prog5.asm
	\masm32\bin\ml /c /coff /Cp prog5.asm
	\masm32\bin\link -entry:main /subsystem:console prog5.obj
	prog5

main4: prog6.asm
	\masm32\bin\ml /c /coff /Cp prog6.asm
	\masm32\bin\link -entry:main /subsystem:console prog6.obj
	prog6

main5: mult.asm
	\masm32\bin\ml /c /coff /Cp mult.asm
	\masm32\bin\link -entry:main /subsystem:console mult.obj
	mult

main6: div.asm
	\masm32\bin\ml /c /coff /Cp div.asm
	\masm32\bin\link -entry:main /subsystem:console div.obj
	div

main7: loop.asm
	\masm32\bin\ml /c /coff /Cp loop.asm
	\masm32\bin\link -entry:main /subsystem:console loop.obj
	loop

main8: proc.asm
	\masm32\bin\ml /c /coff /Cp proc.asm
	\masm32\bin\link -entry:main /subsystem:console proc.obj
	proc


main9: for_loop.asm
	\masm32\bin\ml /c /coff /Cp for_loop.asm
	\masm32\bin\link -entry:main /subsystem:console for_loop.obj
	for_loop

main10: procedure.asm
	\masm32\bin\ml /c /coff /Cp procedure.asm
	\masm32\bin\link -entry:main /subsystem:console procedure.obj
	procedure

main11: f_loop.asm
	\masm32\bin\ml /c /coff /Cp f_loop.asm
	\masm32\bin\link -entry:main /subsystem:console f_loop.obj
	f_loop

main12: prog1_labtest3.asm
	\masm32\bin\ml /c /coff /Cp prog1_labtest3.asm
	\masm32\bin\link -entry:main /subsystem:console prog1_labtest3.obj
	prog1_labtest3

main13: prog2_labtest3.asm
	\masm32\bin\ml /c /coff /Cp prog2_labtest3.asm
	\masm32\bin\link -entry:main /subsystem:console prog2_labtest3.obj
	prog2_labtest3

main14: vow.asm
	\masm32\bin\ml /c /coff /Cp vow.asm
	\masm32\bin\link -entry:main /subsystem:console vow.obj
	vow