%option noyywrap
%{
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	#include "sample1_labtest2.tab.h"
    
	
	int lineno = 1; // initialize to 1
	void yyerror();
%}

alpha     [a-zA-Z]
digit     [0-9]
alnum     {alpha}|{digit}
print     [ -~]

ID        {alpha}{alnum}*
ICONST    [0-9]{digit}*
FCONST    {digit}*"."{digit}+
CCONST    (\'{print}\')
%%

"//".*        { } 

"int"       { return INT; }
"double"    { return DOUBLE; }
"char"		{ return CHAR; }
"main"      { return MAIN; }
"if"		{return IF;}
"else if"   {return ELSEIF;}
"else"		{return ELSE;}
"for"       {return FOR;}
"++"        {return INCR;}
"--"        {return DECR;}
"+"       { return ADDOP; }
"-"       { return SUBOP; }
"*"       { return MULOP; }
"/"       { return DIVOP; }
"=="      { return EQUOP; }
">="       { return EGT; }
"<="       { return ELT; }
">"       { return GT; }
"<"       { return LT; }
"("       { return LPAREN; }
")"       { return RPAREN; }
"{"       { return LBRACE; }
"}"       { return RBRACE; }
";"       { return SEMI; }
"="       { return ASSIGN; }

{ID}        { return ID;}
{ICONST}    { return ICONST;}
{FCONST}    { return FCONST;}
{CCONST}    { return CCONST;}

"\n"        { lineno += 1; }
[ \t\r\f]+  
.  { yyerror("Unrecognized character"); }
